### ISSUE TITLE
Add run instructions

### ISSUE THREAD

**Issue by AceofSpades5757** [jamessizeland/tauri-chess#10]
It looks like it's designed to be run using `npm`, although I usually use Tauri with frontend frameworks like Yew. It'd be nice to have some instructions to run so I can checkout what looks to be a very interesting project.

**Comment by jamessizeland** [comment]
Will do! In brief I install node modules with Yarn package manager, the command for which is just "yarn", then run "yarn tauri dev" to spin up the full stack app in dev mode.
